config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "haikus#index"
  resources :haikus, only: [:index, :new, :create, :show, :destroy]
  resources :users, only: [:index, :show]
  resources :favorites, only: [:index, :create, :destroy]
  resources :users do
    member do
     get :following, :followed
    end
  end
  resources :follows, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :haiku

  validates :user_id, presence: true
  validates :haiku_id, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :following, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :followed_id, presence: true
  validates :following_id, presence: true
end

app/models/haiku.rb
class Haiku < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  with_options presence: true do
    validates :kami, :naka, :simo
  end

  class << self
    def within_box(distance, latitude, longitude)
      distance = distance
      center_point = [latitude, longitude]
      box = Geocoder::Calculations.bounding_box(center_point, distance)
      within_bounding_box(box)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :haikus
  has_many :favorites, dependent: :destroy
  has_many :fav_haikus, through: :favorites, source: :haiku
  has_many :following_relationships, foreign_key: 'followed_id', class_name: 'Follow', dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :followed_relationships, foreign_key: 'following_id', class_name: 'Follow', dependent: :destroy
  has_many :followeds, through: :followed_relationships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  def following?(other_user)
    followings.include?(other_user)
  end

  def follow(other_user)
    following_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :pick_out_ward, :pick_out_city, :pick_out_prefecture

  def pick_out_ward(address)
    num = address.index(',')
    address.slice(0, num)
  end

  def pick_out_city(address)
    ward_num = address.index(',')
    num = address.index(',', (ward_num + 1))
    address.slice((ward_num + 2), ((num - 1) - (ward_num + 1)))
  end

  def pick_out_prefecture(address)
    ward_num = address.index(',')
    city_num = address.index(',', (ward_num + 1))
    num = address.index(',', (city_num + 1))
    address.slice((city_num + 2), ((num - 1) - (city_num + 1)))
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.where(['user_id LIKE(?)', "%#{current_user.id}%"]).limit(30)
  end

  def create
    @favorite = Favorite.new(user_id: current_user.id, haiku_id: params[:haikuId])
    if @favorite.save
      respond_to do |format|
        format.json
      end
    end
  end

  def destroy
    @haiku = Haiku.find(params[:haikuId])
    favorites = @haiku.favorites
    favorites.each do |favorite|
      @favorite = Favorite.find(favorite.id) if favorite.user_id == current_user.id
    end
    if @favorite.destroy
      respond_to do |format|
        format.json
      end
    end
  end

  private

  def favorite_params
    params.merge(user_id: current_user.id, haiku_id: params[:haikuId])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    @friends = Follow.where(['followed_id LIKE(?)', "%#{current_user.id}%"])
  end

  def create
    @user = User.find(params[:follow][:following_id])
    current_user.follow(@user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @user = User.find(params[:follow][:following_id])
    current_user.unfollow(@user)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  def index
    latitude = params[:latitude]
    longitude = params[:longitude]
    distance = params[:distance]
    @haikus = Haiku.within_box(distance, latitude, longitude).order(id: :DESC).limit(100)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @haiku = Haiku.new
  end

  def create
    @haiku = Haiku.new(haiku_params)
    if @haiku.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @haiku = Haiku.find(params[:id])
    @fav_count = @haiku.favorites.count
  end

  def destroy
    @haiku = Haiku.find(params[:id])
    if @haiku.destroy
      redirect_to root_path
    end
  end

  private

  def haiku_params
    params.require(:haiku).permit(:kami, :naka, :simo).merge(user_id: current_user.id, latitude: params[:latitude], longitude: params[:longitude])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @haikus = Haiku.where(['user_id LIKE(?)', "%#{current_user.id}%"])
  end

  def show
    @user = User.find(params[:id])
    @haikus = Haiku.where(['user_id LIKE(?)', "%#{params[:id]}%"])
  end

  def like
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorites/index.html.haml
.haiku-user-top
  = link_to users_path do
    = icon('fa', 'user', class: "haiku-top__icon")
  .haiku-user-top__user-name
    %span= current_user.name
    %span> さんのお気に入り俳句一覧
.haiku-middle
  - @favorites.each.reverse_each do |fav|
    .haiku-middle__contents
      .haiku-middle__contents__content
        .haiku-middle__contents__content__left
          .haiku-middle__contents__content__left__name
            = link_to user_path(fav.haiku.user.id) do
              %span=fav.haiku.user.name
              %span> さん
          .haiku-middle__contents__content__left__haiku
            %span=pick_out_prefecture(fav.haiku.address)
            %span>=pick_out_city(fav.haiku.address)
            %span=pick_out_ward(fav.haiku.address)
            %span> で一句詠みました。
            %span.haiku-created-at=time_ago_in_words(fav.haiku.created_at)
        = link_to haiku_path(fav.haiku.id) do
          .haiku-middle__contents__content__right
            .haiku-middle__contents__content__right__haidoku
              拝読
.haiku-btn

= icon('fa', 'arrow-circle-down', class: "scroll-bottom__icon")

app/views/follows/create.js.erb
$("#follow_form").empty();
$("#follow_form").html("<%= j(render("users/unfollow")) %>");

app/views/follows/destroy.js.erb
$("#follow_form").empty();
$("#follow_form").html("<%= j(render("users/follow")) %>");

app/views/follows/index.html.haml
.haiku-top
  = link_to users_path do
    = icon('fa', 'user', class: "haiku-top__icon")
  .haiku-user-top__user-name
    %span 友達リスト
.haiku-middle
  - @friends.each.reverse_each do |friend|
    .haiku-middle__contents
      .haiku-middle__contents__content
        .haiku-middle__contents__content__left
          .haiku-middle__contents__content__left__name
            = link_to user_path(friend.following.id) do
              %span=friend.following.name
              %span> さん
          .haiku-middle__contents__content__left__haiku
            %span>今までに
            %span=friend.following.haikus.count
            %span> 個の俳句を詠んでいます。
.haiku-btn

= icon('fa', 'arrow-circle-down', class: "scroll-bottom__icon")

app/views/haikus/index.html.haml
.haiku-top
  = link_to users_path do
    = icon('fa', 'user', class: "haiku-top__icon")
  = link_to new_haiku_path, class: "create-haiku" do
    = icon('fa', 'edit', class: "haiku-top__create-icon")
  .haiku-top__top-title
    %span 現在地から
    %select
      %option{value: 1} 1
      %option{value: 5, selected: "selected"} 5
      %option{value: 10} 10
      %option{value: 30} 30
      %option{value: 100} 100
      %option{value: 300} 300
      %option{value: 500} 500
      %option{value: 1000} 1000
      %option{value: 2000} 2000
      %option{value: 3000} 3000
    %span km以内の俳句
.haiku-middle
.haiku-btn

= icon('fa', 'arrow-circle-down', class: "scroll-bottom__icon")

app/views/haikus/new.html.haml
.haiku-top
  = link_to root_path, class: "mypage" do
    = icon('fa', 'home')
  .haiku-top__new-title
    一句詠んでください
.haiku-new-middle
  - if @haiku.errors.any?
    #error_explanation
      %ul
        - @haiku.errors.full_messages.each do |message|
          %li= message
  .haiku-new-middle__kami
    .haiku-new-middle__kami__content
  .haiku-new-middle__naka
    .haiku-new-middle__naka__content
  .haiku-new-middle__simo
    .haiku-new-middle__simo__content
.haiku-new-btn
  = form_with model: @haiku, id: 'haiku-form', local: true do |f|
    .form-content
      .form-content__kami
        上の句：
        = f.text_field :kami, class: 'form-kami', maxlength:"15"
    .form-content
      .form-content__naka
        中の句：
        = f.text_field :naka, class: 'form-naka', maxlength:"20"
    .form-content
      .form-content__simo
        下の句：
        = f.text_field :simo, class: 'form-simo', maxlength:"15"
    .form-content-submit
      = f.submit "詠む", class: "submit-haiku"

app/views/haikus/show.html.haml
.haiku-top
  = link_to root_path, class: "mypage" do
    = icon('fa', 'home')
  - if current_user == @haiku.user
    = link_to haiku_path(@haiku.id), method: :delete, data: { confirm: '削除しますか？' }, class: "create-haiku" do
      = icon('fa', 'trash', class: "haiku-top__create-icon")
  .haiku-top__user-name
    = link_to user_path(@haiku.user.id) do
      %span= @haiku.user.name
      %span>さん
.haiku-show-middle
  .haiku-show-middle__kami
    .haiku-show-middle__kami__content
      = @haiku.kami
  .haiku-show-middle__naka
    .haiku-show-middle__naka__content
      = @haiku.naka
  .haiku-show-middle__simo
    .haiku-show-middle__simo__content
      = @haiku.simo
.haiku-show-btn
  .haiku-show-btn__favorite
    = icon('fa', 'star')
    = @fav_count
  .haiku-show-btn__created-at
    %span= pick_out_prefecture(@haiku.address)
    %span>=pick_out_city(@haiku.address)
    %span=pick_out_ward(@haiku.address)
    &ensp;
    %span= @haiku.created_at.strftime("%Y年 %m月%d日 %H時%M分")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Senryu27914</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_follow.html.haml
= form_with(model: current_user.following_relationships.build) do |f|
  = f.hidden_field :following_id, value: @user.id
  = f.submit "フォロー", class: "btn btn-outline-secondary"

app/views/users/_google-map.html.erb
<div id='map'></div>

<style>
#map{
  height: 80vh;
}
</style>


  <script>
  function initMap(){
    let map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 39.061333, lng: 137.855614},
      zoom: 5,
      styles: [
    {
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            },
            {
                "color": "#f49f53"
            }
        ]
    },
    {
        "featureType": "landscape",
        "stylers": [
            {
                "color": "#f9ddc5"
            },
            {
                "lightness": -7
            }
        ]
    },
    {
        "featureType": "road",
        "stylers": [
            {
                "color": "#813033"
            },
            {
                "lightness": 43
            }
        ]
    },
    {
        "featureType": "poi.business",
        "stylers": [
            {
                "color": "#645c20"
            },
            {
                "lightness": 38
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "color": "#1994bf"
            },
            {
                "saturation": -69
            },
            {
                "gamma": 0.99
            },
            {
                "lightness": 43
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#f19f53"
            },
            {
                "weight": 1.3
            },
            {
                "visibility": "on"
            },
            {
                "lightness": 16
            }
        ]
    },
    {
        "featureType": "poi.business"
    },
    {
        "featureType": "poi.park",
        "stylers": [
            {
                "color": "#645c20"
            },
            {
                "lightness": 39
            }
        ]
    },
    {
        "featureType": "poi.school",
        "stylers": [
            {
                "color": "#a95521"
            },
            {
                "lightness": 35
            }
        ]
    },
    {},
    {
        "featureType": "poi.medical",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#813033"
            },
            {
                "lightness": 38
            },
            {
                "visibility": "off"
            }
        ]
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
        "elementType": "labels"
    },
    {
        "featureType": "poi.sports_complex",
        "stylers": [
            {
                "color": "#9e5916"
            },
            {
                "lightness": 32
            }
        ]
    },
    {},
    {
        "featureType": "poi.government",
        "stylers": [
            {
                "color": "#9e5916"
            },
            {
                "lightness": 46
            }
        ]
    },
    {
        "featureType": "transit.station",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "transit.line",
        "stylers": [
            {
                "color": "#813033"
            },
            {
                "lightness": 22
            }
        ]
    },
    {
        "featureType": "transit",
        "stylers": [
            {
                "lightness": 38
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#f19f53"
            },
            {
                "lightness": -10
            }
        ]
    },
    {},
    {},
    {}
]
    });
  <% haikus.each do |haiku| %>
    <% if haiku.latitude != nil %>
    let contentString_<%= haiku.id %>  = '<%= link_to "#{pick_out_city(haiku.address)}で一句", haiku_path(haiku.id) %>';
    let infowindow_<%= haiku.id %>  = new google.maps.InfoWindow({
        content: contentString_<%= haiku.id %>
      });
    let marker_<%= haiku.id %> = new google.maps.Marker({
      position: new google.maps.LatLng(<%= haiku.latitude %>, <%= haiku.longitude %>),
      draggable: false,
      map: map,
      icon: {
        url: '/haiku.png',
        scaledSize: new google.maps.Size(30, 30)
      },
      animation: google.maps.Animation.DROP
      });
    marker_<%= haiku.id %>.addListener('click', function() {
          infowindow_<%= haiku.id %> .open(map, marker_<%= haiku.id %>);
    });
    <% end %>
  <% end %>
  };
  </script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.credentials.GOOGLE_MAP_KEY%>&callback=initMap" async defer></script>

app/views/users/_unfollow.html.haml
= form_with(model: current_user.following_relationships.find_by(following_id: @user.id),method: :delete) do |f|
  = f.hidden_field :following_id
  = f.submit "フォロー解除", class: "unfollow"

app/views/users/index.html.haml
.haiku-user-top
  = link_to root_path, class: "mypage" do
    = icon('fa', 'home')
  .haiku-user-top__user-name
    %span マイページ
.haiku-middle
  = render partial: 'google-map', locals: { haikus: @haikus }
.haiku-btn
  = link_to favorites_path do
    .haiku-btn__favorite
      %span お気に入りの俳句
  = link_to destroy_user_session_path, method: :delete do
    .haiku-btn__logout
      %span ログアウト
  = link_to follows_path do
    .haiku-btn__follow
      %span 友達リスト

app/views/users/show.html.haml
.haiku-user-top
  = link_to users_path do
    = icon('fa', 'user', class: "haiku-top__icon")
  .haiku-user-top__user-name
    %span= @user.name
    %span>さんの俳句一覧
  - if  @user != current_user
    #follow_form
      - if current_user.following?(@user)
        = render "unfollow"
      - else
        = render "follow"
.haiku-middle
  = render partial: 'google-map', locals: { haikus: @haikus }
.haiku-btn